### ISSUE TITLE
ReadTheDocs an CircleCI errors

### ISSUE THREAD

**Issue by gertjan123** [gertjan123/Met4FoF-redundancy#14]
**ReadTheDocs Error:**

  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/checkouts/master/Met4FoF_redundancy/agentMFred/metrological_streams_v2.py", line 50, in __init__
    value_unc=value_unc, time_unc=time_unc
TypeError: __init__() got an unexpected keyword argument 'value_unc'

**CircleCI Error:**
test_redundancy/test_tutorials.py:1: in <module>
    from Met4FoF_redundancy_tutorials.redundancyAgents_tutorial_1 import main as tut1
E   ImportError: cannot import name 'main' from 'Met4FoF_redundancy_tutorials.redundancyAgents_tutorial_1' (/home/circleci/repo/Met4FoF_redundancy_tutorials/redundancyAgents_tutorial_1.py)
=============================== warnings summary ===============================
venv/lib/python3.8/site-packages/agentMET4FOF/metrological_streams.py:117
  /home/circleci/repo/venv/lib/python3.8/site-packages/agentMET4FOF/metrological_streams.py:117: UserWarning:
  
  No uncertainty generator function specified. Setting to default (zero).

**Comment by anupam-prasad** [comment]
The first error has been fixed in a previous update. The most recent pull request #15 has a fix for the CircleCI Error.

**Comment by gertjan123** [comment]
Thank you for fixing the CircleCI error.
ReadTheDocs is still not working:

Running Sphinx v3.5.3
loading translations [en]... done
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 4 source files that are out of date
updating environment: [new config] 4 added, 0 changed, 0 removed
reading sources... [ 25%] getting-started_doc
reading sources... [ 50%] index
reading sources... [ 75%] redundancy1_doc
reading sources... [100%] redundancyAgents1_doc

WARNING: autodoc: failed to import module 'redundancyAgents1' from module 'Met4FoF_redundancy.agentMFred'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/envs/master/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 71, in import_module
    return importlib.import_module(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/envs/master/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/checkouts/master/Met4FoF_redundancy/agentMFred/redundancyAgents1.py", line 18, in <module>
    class MetrologicalMultiWaveGeneratorAgent(MetrologicalAgent):
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/checkouts/master/Met4FoF_redundancy/agentMFred/redundancyAgents1.py", line 28, in MetrologicalMultiWaveGeneratorAgent
    def init_parameters(self, signal: MetrologicalMultiWaveGenerator = MetrologicalMultiWaveGenerator(), **kwargs):
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/checkouts/master/Met4FoF_redundancy/agentMFred/metrological_streams_v2.py", line 50, in __init__
    value_unc=value_unc, time_unc=time_unc
TypeError: __init__() got an unexpected keyword argument 'value_unc'

WARNING: autodoc: failed to import module 'redundancyAgents_tutorial_1' from module 'Met4FoF_redundancy_tutorials'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/envs/master/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 71, in import_module
    return importlib.import_module(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/envs/master/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/checkouts/master/Met4FoF_redundancy_tutorials/redundancyAgents_tutorial_1.py", line 16, in <module>
    from Met4FoF_redundancy.agentMFred.redundancyAgents1 import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/checkouts/master/Met4FoF_redundancy/agentMFred/redundancyAgents1.py", line 18, in <module>
    class MetrologicalMultiWaveGeneratorAgent(MetrologicalAgent):
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/checkouts/master/Met4FoF_redundancy/agentMFred/redundancyAgents1.py", line 28, in MetrologicalMultiWaveGeneratorAgent
    def init_parameters(self, signal: MetrologicalMultiWaveGenerator = MetrologicalMultiWaveGenerator(), **kwargs):
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/checkouts/master/Met4FoF_redundancy/agentMFred/metrological_streams_v2.py", line 50, in __init__
    value_unc=value_unc, time_unc=time_unc
TypeError: __init__() got an unexpected keyword argument 'value_unc'

WARNING: autodoc: failed to import module 'redundancyAgents_tutorial_2' from module 'Met4FoF_redundancy_tutorials'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/envs/master/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 71, in import_module
    return importlib.import_module(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/envs/master/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/checkouts/master/Met4FoF_redundancy_tutorials/redundancyAgents_tutorial_2.py", line 13, in <module>
    from Met4FoF_redundancy.agentMFred.redundancyAgents1 import MetrologicalMultiWaveGeneratorAgent, RedundancyAgent
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/checkouts/master/Met4FoF_redundancy/agentMFred/redundancyAgents1.py", line 18, in <module>
    class MetrologicalMultiWaveGeneratorAgent(MetrologicalAgent):
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/checkouts/master/Met4FoF_redundancy/agentMFred/redundancyAgents1.py", line 28, in MetrologicalMultiWaveGeneratorAgent
    def init_parameters(self, signal: MetrologicalMultiWaveGenerator = MetrologicalMultiWaveGenerator(), **kwargs):
  File "/home/docs/checkouts/readthedocs.org/user_builds/met4fof-redundancy/checkouts/master/Met4FoF_redundancy/agentMFred/metrological_streams_v2.py", line 50, in __init__
    value_unc=value_unc, time_unc=time_unc
TypeError: __init__() got an unexpected keyword argument 'value_unc'

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 25%] getting-started_doc
writing output... [ 50%] index
writing output... [ 75%] redundancy1_doc
writing output... [100%] redundancyAgents1_doc

generating indices... genindex py-modindex done
highlighting module code... [ 33%] Met4FoF_redundancy.MFred.redundancy1
highlighting module code... [ 66%] Met4FoF_redundancy.agentMFred.metrological_streams_v2
highlighting module code... [100%] test_redundancy.test_MFred

writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build finished with problems, 3 warnings.
Updating searchtools for Read the Docs search...

**Comment by anupam-prasad** [comment]
It could be that you're using an older version of AgentMET4FOF. I'm currently using 0.6.1. The keywords `value_unc` and `exp_unc` are recent additions.
